version: "3.7"
services:
  server:
    image: iuhhdev/togetherjs-server
    ports:
      - 8080:8080
    # environment:
      # - HOST="0.0.0.0"
    network_mode: bridge
    restart: always
  client:
    image: iuhhdev/togetherjs-client
    ports:
      - 4200:80
    network_mode: bridge
    restart: always
networks:
  default:
    external:
      name: bridge